Fist iteration
Jlogblpb/go-sprint-four pull request #1
Opened 2023-12-12 18:23 UTC by Jlogblpb

2023-12-13 04:48 UTC, just-musha requested changes
Привет! Стоит проверить формулы калорий running и swimming и для проверки прогнать локально тесты (оставила комментарий).

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +		speed := meanSpeed(action, duration)                           // вызовите здесь необходимую функцию
у swimming определена своя функция, давай её вызовем тут

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +	return ((runningCaloriesMeanSpeedMultiplier * (meanSpeed(action, duration)) * runningCaloriesMeanSpeedShift) * weight / mInKm * duration * minInH)
Внешние скобки можно убрать, они ни на что не влияют

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +	return ((swimmingMeanSpeed(lenghtPool, countPool, duration) + 1.1) * swimmingCaloriesWeightMultiplier * weight * duration)
И здесь можно убрать внешние скобки

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +	return ((runningCaloriesMeanSpeedMultiplier * (meanSpeed(action, duration)) * runningCaloriesMeanSpeedShift) * weight / mInKm * duration * minInH)
Стоит проверить формулу, все ли приведения сделаны.

Для проверки - в основном репозитории добавили файл с тестами `ftracker_test.go` https://github.com/Yandex-Practicum/go-sprint-four   Попробуй скопировать его к себе и прогнать тесты локально

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +	return ((walkingCaloriesWeightMultiplier*weight + (math.Pow((meanSpeed(action, duration)*kmhInMsec), 2)/height)*walkingSpeedHeightMultiplier*weight) * duration * minInH)
И здесь внешние скобки

2023-12-13 04:48 UTC, just-musha commented on ftracker.go
> +	return ((swimmingMeanSpeed(lenghtPool, countPool, duration) + 1.1) * swimmingCaloriesWeightMultiplier * weight * duration)
Вместо 1.1 лучше использовать специальную константу

2023-12-15 05:27 UTC, just-musha approved these changes
Супер, спасибо. Принято

2023-12-21 19:10 UTC, closed without merging

2023-12-21 19:10 UTC, Jlogblpb commented
Вам спасибо!